### ISSUE TITLE
Looking forward to integrating easy_refresh

### ISSUE THREAD

**Issue by Pluto1219** [K9i-0/riverpod_paging_utils#15]
Thank you so much for developing such a great tool, it helped me tremendously during my development process. However, I found during use that the loading animation effect cannot be customized at present.

I previously discovered a great refresh plugin, [easy_refresh](https://pub.dev/packages/easy_refresh), which provides a lot of interesting animation effects.

It would be great if you could integrate easy_refresh into your utils. In this way, we can implement more functions through state.refreshController, such as calling callRefresh, etc.

Thank you again for all your hard work!

**Comment by K9i-0** [comment]
You can customize the UI of the `PagingHelperView` using a `ThemeExtension` called `PagingHelperViewTheme`. I've added a section to the README with more details and examples 👍 

https://github.com/K9i-0/riverpod_paging_utils?tab=readme-ov-file#ui-customization

**Comment by Pluto1219** [comment]
> You can customize the UI of the `PagingHelperView` using a `ThemeExtension` called `PagingHelperViewTheme`. I've added a section to the README with more details and examples 👍
> 
> https://github.com/K9i-0/riverpod_paging_utils?tab=readme-ov-file#ui-customization
> 
> The pull to refresh UI cannot be customized at this time, but would you like to customize it as well?

Addition of construction functions, refinement and control functions, use functions to sequence the ground touching renewal operations. It is possible to actually see a similar function, for example provider.refreshIndicatorController?.callRefresh(). After the instruction, the page will be updated and displayed, and the video will be displayed. Thank you again for your support of this general.(My English is not good, this paragraph was translated through Google, please forgive me if the sentences don't make sense.)

**Comment by Pluto1219** [comment]
> You can customize the UI of the `PagingHelperView` using a `ThemeExtension` called `PagingHelperViewTheme`. I've added a section to the README with more details and examples 👍
> 
> https://github.com/K9i-0/riverpod_paging_utils?tab=readme-ov-file#ui-customization
> 
> The pull to refresh UI cannot be customized at this time, but would you like to customize it as well?

ユーザーがプログラムでリフレッシュ操作をトリガーできるように、より詳細なリフレッシュ制御機能を追加することをお勧めします。 Provider.refreshIndicatorController?.callRefresh() など、同様の機能を実現するメソッドの実装を検討できます。このメソッドを呼び出した後、ページは更新操作をトリガーし、読み込みアニメーションを自動的に表示します。これにより、ユーザー エクスペリエンスが大幅に向上します。ありがとうございます。 （私の英語は苦手です。Googleで翻訳したものです。意味が分からない場合は、補足してください。）

**Comment by K9i-0** [comment]
新しくデフォルトのRefreshIndicatorを無効にする機能を追加し、exampleにeasy_refreshを使うサンプルを追加しました。目的は達成できそうですか？

https://github.com/K9i-0/riverpod_paging_utils?tab=readme-ov-file#advanced-customization

**Comment by Pluto1219** [comment]
> 新しくデフォルトのRefreshIndicatorを無効にする機能を追加し、exampleにeasy_refreshを使うサンプルを追加しました。目的は達成できそうですか？
> 
> https://github.com/K9i-0/riverpod_paging_utils?tab=readme-ov-file#advanced-customization

あなたは私の心の中のウルトラマンです。谢谢你 :)
